version: '3.7'

services:
  # Define the pgadmin service
  pgadmin:
    # Use the latest dpage/pgadmin4 image
    image: dpage/pgadmin4:latest
    # Set the container name
    container_name: pgadmin4_web_server
    # Define environment variables for pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}   # Set default email
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # Set default password
      PGADMIN_DEFAULT_EMAIL1: ${PGADMIN_DEFAULT_EMAIL1}   # Set additional email 1
      PGADMIN_DEFAULT_PASSWORD1: ${PGADMIN_DEFAULT_PASSWORD1}  # Set additional password 1
      PGADMIN_DEFAULT_EMAIL2: ${PGADMIN_DEFAULT_EMAIL2}   # Set additional email 2
      PGADMIN_DEFAULT_PASSWORD2: ${PGADMIN_DEFAULT_PASSWORD2}  # Set additional password 2
      PGADMIN_DEFAULT_EMAIL3: ${PGADMIN_DEFAULT_EMAIL3}   # Set additional email 3
      PGADMIN_DEFAULT_PASSWORD3: ${PGADMIN_DEFAULT_PASSWORD3}  # Set additional password 3
      PGADMIN_DEFAULT_EMAIL4: ${PGADMIN_DEFAULT_EMAIL4}   # Set additional email 4
      PGADMIN_DEFAULT_PASSWORD4: ${PGADMIN_DEFAULT_PASSWORD4}  # Set additional password 4
      PGADMIN_LISTEN_PORT: 80  # Set pgAdmin listen port
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json  # Specify server configuration file path
    # Expose port 8080 on the host and map it to port 80 in the container
    ports:
      - "8080:80"
    # Mount the servers.json file from the host to the container as read-only
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - /etc/localtime:/etc/localtime:ro  # Share time from host to container
    # Ensure the container restarts automatically
    restart: always
    # Connect the container to the default bridge network
    networks:
      - default

# Define the default bridge network
networks:
  default:
    driver: bridge
