version: '3.7'

services:
  # Define the pgadmin service
  pgadmin:
    # Use the latest dpage/pgadmin4 image
    image: dpage/pgadmin4:latest
    # Set the container name
    container_name: pgadmin4_web_server
    # Define environment variables for pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}   # Set default email
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # Set default password
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json  # Specify server configuration file path
      PGADMIN_ADDITIONAL_EMAILS: ${PGADMIN_ADDITIONAL_EMAILS}   # Additional email addresses
      PGADMIN_ADDITIONAL_PASSWORDS: ${PGADMIN_ADDITIONAL_PASSWORDS}  # Additional passwords
    # Expose port 8080 on the host and map it to port 80 in the container
    ports:
      - "8080:80"
    # Mount the servers.json file from the host to the container as read-only
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - /etc/localtime:/etc/localtime:ro  # Share time from host to container
    # Ensure the container restarts automatically
    restart: always
    # Connect the container to the default bridge network
    networks:
      - default

# Define the default bridge network
networks:
  default:
    driver: bridge
