version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_server
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8080:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime:ro
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
